# Generated by Django 3.0 on 2020-05-24 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='genuine',
            field=models.ManyToManyField(blank=True, related_name='img_genuines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='genuine',
            field=models.ManyToManyField(blank=True, related_name='msg_genuines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='genuine',
            field=models.ManyToManyField(blank=True, related_name='post_genuines', to=settings.AUTH_USER_MODEL),
        ),
    ]
