# Generated by Django 3.0 on 2020-05-24 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20200525_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='spam',
            field=models.ManyToManyField(blank=True, related_name='img_spames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='spam',
            field=models.ManyToManyField(blank=True, related_name='msg_spames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='spam',
            field=models.ManyToManyField(blank=True, related_name='post_spames', to=settings.AUTH_USER_MODEL),
        ),
    ]
