# Generated by Django 3.0 on 2020-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200509_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='img',
            name='fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
