# Generated by Django 3.0 on 2020-05-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200529_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='advertisiment',
            new_name='advertisement',
        ),
    ]
