# Generated by Django 3.0 on 2020-05-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200509_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='img',
            name='fake',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='fake',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
