# Generated by Django 3.0 on 2020-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200529_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadvertisment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
