# Generated by Django 3.0 on 2020-05-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200529_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='advertisement',
        ),
        migrations.AddField(
            model_name='postadvertisment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
