# Generated by Django 3.0 on 2020-05-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200529_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postadvertisment',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.PostAdvertisment'),
        ),
    ]
