# Generated by Django 3.0 on 2020-05-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200529_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadvertisment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postad', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postadvertisement', to='posts.PostAdvertisment'),
        ),
    ]
