# Generated by Django 3.0 on 2020-05-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200529_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postadvertisment',
            name='post',
        ),
    ]
