# Generated by Django 3.0 on 2020-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200412_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='unread',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
