# Generated by Django 3.0 on 2020-04-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_comment_unread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='unread',
        ),
    ]
