# Generated by Django 3.0 on 2020-04-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200418_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='fake_picture'),
        ),
    ]
