# Generated by Django 3.0 on 2020-04-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_message_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='picture',
        ),
    ]
