# Generated by Django 3.0 on 2020-04-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_message_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tags',
        ),
    ]
