# Generated by Django 3.0 on 2020-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_message_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='fake_picture')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='picture',
        ),
    ]
