# Generated by Django 3.0 on 2020-04-30 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_auto_20200424_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='img', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
