# Generated by Django 3.0 on 2020-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('content', models.CharField(default=True, max_length=128)),
            ],
        ),
    ]
