# Generated by Django 2.2.12 on 2020-05-04 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ssEmail', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1024)),
                ('token', models.CharField(max_length=75, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dev_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
