# Generated by Django 2.2.12 on 2020-05-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developers',
            name='dev_user',
        ),
        migrations.AddField(
            model_name='developers',
            name='dev_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
