# Generated by Django 2.2.12 on 2020-05-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20200504_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
