# Generated by Django 2.2.12 on 2020-05-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_auto_20200504_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='token',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
