# Generated by Django 3.0 on 2020-05-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_profile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
    ]
