# Generated by Django 3.0 on 2020-05-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_profile_scrapcoins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Licenced',
            field=models.BooleanField(default=False),
        ),
    ]
