# Generated by Django 3.0 on 2020-05-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_remove_profile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
